name: Node.js CD

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest

    needs: test

    steps:
      - run: yarn build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
